# Generated by Django 6.0.2 on 2026-02-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
