# Generated by Django 6.0.2 on 2026-02-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.AlterField(
            model_name='game',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='games/'),
            preserve_default=False,
        ),
    ]
