# Generated by Django 6.0.2 on 2026-02-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_review_unique_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-id']},
        ),
    ]
